### ISSUE TITLE
Total of estimated minutes - iPad Issue

### ISSUE THREAD

**Issue by timstringer** [unlocked2412/Omni-Automation#3]
The “Total of estimated minutes” plug-in works in the OmniFocus for Mac, but I haven't been able to get it to work in OmniFocus for iPad. Specifically, the menu item is grayed out, even if items are selected in the outline. Thanks!

**Comment by unlocked2412** [comment]
Thanks for the report. Will look into it.

**Comment by timstringer** [comment]
Great. Thanks very much!

**Comment by unlocked2412** [comment]
Just pushed an update. The script now works on iOS/iPadOS.
