### ISSUE TITLE
Total of estimated minutes - request: change extension to omnifocusjs

### ISSUE THREAD

**Issue by timstringer** [unlocked2412/Omni-Automation#4]
Thanks for sharing the "Total of estimated minutes" plug-in. I use it regularly. Consider changing the extension from "omnijs" to "omnifocusjs" so that the plug-in can be installed by double-clicking on the script file.

**Comment by unlocked2412** [comment]
Done !

**Comment by timstringer** [comment]
Great. Thanks very much!
