### ISSUE TITLE
Statistics: Inbox count doesn’t include actions in action groups

### ISSUE THREAD

**Issue by multigreg** [unlocked2412/Omni-Automation#7]
This is a very minor issue. If you have created action groups in your Inbox (starting to structure the task before moving it to a project), their child actions are not included in the Inbox task count.

This is because of the behaviour of the `inInbox` property. From API:
> var inInbox → Boolean read-only
> True if the task is a direct child of the inbox, but not if the task is contained by another task that is in the inbox.

A solution could be to find the topmost ancestor of each task object and check the property on that.

**Comment by unlocked2412** [comment]
Thanks for the report. I'll look into this.

**Comment by unlocked2412** [comment]
I think that's not true. I am deriving the number of inbox tasks using this function; traversing the whole hierarchy of inbox tasks. Could you check again and report ?

```
// inboxTasks :: () -> [OFTask]
const inboxTasks = () => {
    const xs = filter(x => x.inInbox)(
        flattenedTasks
    );
    return concatMap(x => {
        const tasks = x.flattenedTasks;
        return 0 === tasks.length ? (
            x
        ) : [x, ...tasks]
    })(xs)
};
```

**Comment by multigreg** [comment]
You are entirely correct. I got confused with my test sets and didn’t look at your function carefully enough. Sorry for the bother!
